apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: work_out
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mhefner/work_out
    targetRevision: HEAD
    path: overlay/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
