apiVersion: apps/v1
kind: Deployment
metadata:
  name: work_out
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work_out
  template:
    metadata:
      labels:
        app: work_out
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: analyzer
        image: mhefner1983/work_out:dev
        ports:
        - containerPort: 80
