apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-out
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-out
  template:
    metadata:
      labels:
        app: work-out
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: work-out
        image: mhefner1983/work_out:dev
        ports:
        - containerPort: 80
