apiVersion: v1
kind: Service
metadata:
  name: work-out
spec:
  type: NodePort
  selector:
    app: work-out
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081  # You can pick any free port between 30000–32767
